package net.perfectdreams.randomroleplaypictures.backend.utils.pictures

import net.perfectdreams.randomroleplaypictures.backend.utils.RoleplayPictures

object DanceRoleplayPictures : RoleplayPictures("dance") {
    init {
        picture("gif_259.gif", GenericMatchType)
        picture("gif_260.gif", GenericMatchType)
        picture("gif_261.gif", GenericMatchType)
        picture("gif_262.gif", GenericMatchType)
        picture("gif_263.gif", GenericMatchType)
        picture("gif_264.gif", GenericMatchType)
        picture("gif_265.gif", GenericMatchType)
        picture("gif_266.gif", GenericMatchType)
        picture("gif_267.gif", GenericMatchType)
        picture("gif_268.gif", GenericMatchType)
        picture("gif_269.gif", GenericMatchType)
        picture("gif_270.gif", GenericMatchType)
        picture("gif_271.gif", GenericMatchType)
        picture("gif_272.gif", GenericMatchType)
        picture("gif_273.gif", GenericMatchType)
        picture("gif_274.gif", GenericMatchType)
        picture("gif_276.gif", GenericMatchType)
        picture("gif_277.gif", GenericMatchType)
        picture("gif_278.gif", GenericMatchType)
        picture("gif_279.gif", GenericMatchType)

        picture("gif_229.gif", BothMatchType)
        picture("gif_230.gif", BothMatchType)
        picture("gif_231.gif", BothMatchType)
        picture("gif_232.gif", BothMatchType)
        picture("gif_233.gif", BothMatchType)
        picture("gif_234.gif", BothMatchType)
        picture("gif_235.gif", BothMatchType)
        picture("gif_236.gif", BothMatchType)
        picture("gif_237.gif", BothMatchType)
        picture("gif_238.gif", BothMatchType)
        picture("gif_239.gif", BothMatchType)

        picture("gif_241.gif", MaleXMaleGenderMatchType)
        picture("gif_242.gif", MaleXMaleGenderMatchType)
        picture("gif_243.gif", MaleXMaleGenderMatchType)
        picture("gif_244.gif", MaleXMaleGenderMatchType)
        picture("gif_245.gif", MaleXMaleGenderMatchType)
        picture("gif_246.gif", MaleXMaleGenderMatchType)
        picture("gif_240.gif", MaleXFemaleGenderMatchType)
        picture("gif_258.gif", FemaleXMaleGenderMatchType)
        picture("gif_247.gif", FemaleXFemaleGenderMatchType)
        picture("gif_248.gif", FemaleXFemaleGenderMatchType)
        picture("gif_249.gif", FemaleXFemaleGenderMatchType)
        picture("gif_250.gif", FemaleXFemaleGenderMatchType)
        picture("gif_251.gif", FemaleXFemaleGenderMatchType)
        picture("gif_252.gif", FemaleXFemaleGenderMatchType)
        picture("gif_253.gif", FemaleXFemaleGenderMatchType)
        picture("gif_254.gif", FemaleXFemaleGenderMatchType)
        picture("gif_255.gif", FemaleXFemaleGenderMatchType)
        picture("gif_256.gif", FemaleXFemaleGenderMatchType)
        picture("gif_257.gif", FemaleXFemaleGenderMatchType)
    }
}