package net.perfectdreams.randomroleplaypictures.backend.utils.pictures

import net.perfectdreams.randomroleplaypictures.backend.utils.RoleplayPictures

object HugRoleplayPictures : RoleplayPictures("hug") {
    init {
        picture("hug-1.gif", BothMatchType)
        picture("hug-2.gif", BothMatchType)
        picture("hug-3.gif", BothMatchType)
        picture("hug-4.gif", BothMatchType)

        picture("hug-1.gif", GenericMatchType)
        picture("hug-2.gif", GenericMatchType)
        picture("hug-3.gif", GenericMatchType)
        picture("hug-4.gif", GenericMatchType)
        picture("hug-5.gif", GenericMatchType)
        picture("hug-6.gif", GenericMatchType)
        picture("hug-7.gif", GenericMatchType)
        picture("hug-8.gif", GenericMatchType)
        picture("hug-9.gif", GenericMatchType)
        picture("hug-10.gif", GenericMatchType)
        picture("hug-11.gif", GenericMatchType)
        picture("hug-12.gif", GenericMatchType)
        picture("hug-13.gif", GenericMatchType)
        picture("hug-14.gif", GenericMatchType)
        picture("hug-15.gif", GenericMatchType)
        picture("hug-16.gif", GenericMatchType)
        picture("hug-17.gif", GenericMatchType)
        picture("hug-18.gif", GenericMatchType)
        picture("hug-19.gif", GenericMatchType)

        picture("hug-1.gif", MaleXFemaleGenderMatchType)
        picture("hug-2.gif", MaleXFemaleGenderMatchType)
        picture("hug-3.gif", MaleXFemaleGenderMatchType)
        picture("hug-4.gif", MaleXFemaleGenderMatchType)
        picture("hug-5.gif", MaleXFemaleGenderMatchType)
        picture("hug-6.gif", MaleXFemaleGenderMatchType)
        picture("hug-7.gif", MaleXFemaleGenderMatchType)
        picture("hug-8.gif", MaleXFemaleGenderMatchType)

        picture("hug-1.gif", MaleXMaleGenderMatchType)
        picture("hug-2.gif", MaleXMaleGenderMatchType)
        picture("hug-3.gif", MaleXMaleGenderMatchType)

        picture("hug-1.gif", FemaleXFemaleGenderMatchType)
        picture("hug-2.gif", FemaleXFemaleGenderMatchType)
        picture("hug-3.gif", FemaleXFemaleGenderMatchType)
        picture("hug-4.gif", FemaleXFemaleGenderMatchType)
        picture("hug-5.gif", FemaleXFemaleGenderMatchType)
        picture("hug-6.gif", FemaleXFemaleGenderMatchType)
        picture("hug-7.gif", FemaleXFemaleGenderMatchType)
        picture("hug-8.gif", FemaleXFemaleGenderMatchType)
        picture("hug-9.gif", FemaleXFemaleGenderMatchType)
        picture("hug-10.gif", FemaleXFemaleGenderMatchType)
        picture("hug-11.gif", FemaleXFemaleGenderMatchType)
        picture("hug-12.gif", FemaleXFemaleGenderMatchType)
        picture("hug-13.gif", FemaleXFemaleGenderMatchType)
        picture("hug-14.gif", FemaleXFemaleGenderMatchType)
        picture("hug-15.gif", FemaleXFemaleGenderMatchType)
        picture("hug-16.gif", FemaleXFemaleGenderMatchType)
        picture("hug-17.gif", FemaleXFemaleGenderMatchType)
        picture("hug-18.gif", FemaleXFemaleGenderMatchType)
        picture("hug-19.gif", FemaleXFemaleGenderMatchType)
        picture("hug-20.gif", FemaleXFemaleGenderMatchType)
        picture("hug-21.gif", FemaleXFemaleGenderMatchType)
        picture("hug-22.gif", FemaleXFemaleGenderMatchType)

        picture("hug-1.gif", FemaleXMaleGenderMatchType)
        picture("hug-2.gif", FemaleXMaleGenderMatchType)
        picture("hug-3.gif", FemaleXMaleGenderMatchType)
        picture("hug-4.gif", FemaleXMaleGenderMatchType)
        picture("hug-5.gif", FemaleXMaleGenderMatchType)
        picture("hug-6.gif", FemaleXMaleGenderMatchType)
        picture("hug-7.gif", FemaleXMaleGenderMatchType)
        picture("hug-8.gif", FemaleXMaleGenderMatchType)
        picture("hug-9.gif", FemaleXMaleGenderMatchType)
        picture("hug-10.gif", FemaleXMaleGenderMatchType)
        picture("hug-11.gif", FemaleXMaleGenderMatchType)
        picture("hug-12.gif", FemaleXMaleGenderMatchType)
        picture("hug-13.gif", FemaleXMaleGenderMatchType)
        picture("hug-14.gif", FemaleXMaleGenderMatchType)
        picture("hug-15.gif", FemaleXMaleGenderMatchType)
    }
}